version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: qpay-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: qpay
      MYSQL_USER: qpay
      MYSQL_PASSWORD: qpay123456
    ports:
      - "3306:3306"

  qpay-app:
    build:
      context: .
    image: qpay-app:latest
    container_name: qpay-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
