database:
  mysql_host: "qpay-mysql"
  mysql_port: 3306
  mysql_username: "root"
  mysql_password: "123456"
  mysql_database: "qpay"
jwt:
  secret: "af97879a-4039-448b-bca4-4228d7755635"
  expiration_hours: 72
server:
  host: "qpay-app"
  port: 8080
bank:
  merchantId: "8a45f66a-f3cd-403b-9deb-31df917e0200"
  baseurl: "https://potential-waffle-5xqpwq556x7345rx-8080.app.github.dev/payment/callback"
