database:
  mysql_host: "localhost"
  mysql_port: 3306
  mysql_username: "your_username"
  mysql_password: "your_password"
  mysql_database: "your_database"
jwt:
  secret: "your_secret"
  expiration_hours: 72
