database:
  mysql_host: "localhost"
  mysql_port: 3306
  mysql_username: "root"
  mysql_password: "123456"
  mysql_database: "qpay"
jwt:
  secret: "af97879a-4039-448b-bca4-4228d7755635"
  expiration_hours: 72
server:
  host: "localhost"
  port: 8080
