database:
  mysql_host: "localhost"
  mysql_port: 3306
  mysql_username: "root"
  mysql_password: "123456"
  mysql_database: "qpay"
jwt:
  secret: "your_secret"
  expiration_hours: 72
server:
  host: "localhost"
  port: 8080
