CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    gateway_id INT NOT NULL,
    amount INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    transaction_time TIMESTAMP ,
    user_id INT NOT NULL,
    callback_url VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    authority VARCHAR(255) UNIQUE NOT NULL,
    bank_authority VARCHAR(255),
    bank_ref_id VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (gateway_id) REFERENCES payment_gateways(id)
);
